### ISSUE TITLE
Error : cannot find module

### ISSUE THREAD

**Issue by sahyre** [yeoman/yeoman.github.io#601]
$ yo --version && bower --version && grunt --version

While I run this command, I got the error below
1.6.0
1.7.7
grunt-cli v0.1.13
module.js:341
    throw err;
    ^

Error: Cannot find module './schema/safe'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\IBM_ADMIN\node_modules\grunt\node_modules\js-yaml\lib\js-yaml\loader.js:8:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

How to resolve this issue?
I use Windows 7 64bit

**Comment by SBoudrias** [comment]
Open an issue on the generator you used. That's not Yeoman related.
