### ISSUE TITLE
node_modules permission issue.

### ISSUE THREAD

**Issue by pzano** [yeoman/yeoman.github.io#650]
Hi, I'm getting a node_modules permission issue although I have already ran chown and chmod in an attempt to fix this. Anyone able to solve this?

`$ yo hubot
/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:321
        throw er
        ^

Error: EACCES: permission denied, scandir '/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at GlobSync._readdir (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:275:41)
    at GlobSync._processReaddir (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:135:22)
    at GlobSync._process (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:130:10)
    at new GlobSync (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:46:10)
    at Function.globSync [as sync] (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/glob/sync.js:24:10)
    at /home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/globby/index.js:55:35
    at Array.reduce (native)
    at Function.module.exports.sync (/home/qbobot/node-v6.2.0-linux-x64/lib/node_modules/yo/node_modules/globby/index.js:54:19)`

node = v6.2.0
npm  = 3.8.9

**Comment by zckrs** [comment]
Not related to Yeoman.
But stop to using sudo for npm install - -global.
