### ISSUE TITLE
Permissions issue ASP.NET Scaffolding on Mac

### ISSUE THREAD

**Issue by jmeier07** [yeoman/yeoman.github.io#688]
I tried to scaffold the web api application using yeoman command:
yo aspnet

When I got the permissions issue, I tried to use sudo before the command:
sudo yo aspnet

No Luck using either. Also tried to change permissions on folders and no joy.

Output:
? What type of application do you want to create? Web API Application
? What's the name of your ASP.NET application? WebAPIApplication
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/Users/jaredmeier/Documents/webAPI/WebAPIApplication'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/usr/local/lib/node_modules/generator-aspnet/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/generator-aspnet/node_modules/mkdirp/index.js:77:24)
    at constructor.writing (/usr/local/lib/node_modules/generator-aspnet/app/index.js:243:16)
    at /usr/local/lib/node_modules/generator-aspnet/node_modules/yeoman-generator/lib/base.js:421:16
    at runCallback (timers.js:628:20)
    at tryOnImmediate (timers.js:601:5)
    at processImmediate [as _immediateCallback] (timers.js:578:5)

**Comment by SBoudrias** [comment]
If you sudo-ed and try to change permissions, then I don't know what to tell you. That's not a bug with Yeoman, it's a permission issue on your computer.
