### ISSUE TITLE
Command-line Arguments and Options

### ISSUE THREAD

**Issue by arisc097** [yeoman/yeoman.github.io#750]
On my project, I am using argument and option. The argument is required and the option is dataservice. When an argument is required, the argument has to be the first argument on command-line. It doesn't work if options precede a required argument. This conflicts with the yo --help guidance.

`$ yo my-project --help`
Usage:
  yo my-project:app [options] <appname> //incorrect?

Options:
  -h,   --help          # Print the generator's options and usage
        --skip-cache    # Do not remember prompt answers             Default: false
        --skip-install  # Do not automatically install dependencies  Default: false
        --dataservice   # Description for dataservice

Arguments:
  appname  # name of the project  Type: String  Required: true

`$ yo my-project --dataservice appname` //fails
`$ yo my-project appname --dataservice` //works

does argument have to come before options?

$ `yo my-project --dataservice appname`
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Did not provide required argument appname!
    at module.exports.<anonymous> (/Users/me/Document/workspace/dp-generators/generator-my-project/node_modules/yeoman-generator/lib/index.js:356:33)
    at Array.forEach (<anonymous>)
    at module.exports.Base.checkRequiredArgs (/Users/me/Document/workspace/dp-generators/generator-my-project/node_modules/yeoman-generator/lib/index.js:352:19)
    at module.exports.Base.parseOptions (/Users/me/Document/workspace/dp-generators/generator-my-project/node_modules/yeoman-generator/lib/index.js:337:8)
    at module.exports.argument (/Users/me/Document/workspace/dp-generators/generator-my-project/node_modules/yeoman-generator/lib/index.js:259:8)
    at new module.exports (/Users/me/Document/workspace/dp-generators/generator-my-project/generators/app/index.js:21:10)
    at Environment.instantiate (/Users/me/.nvm/versions/node/v8.9.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:403:12)
    at Environment.create (/Users/me/.nvm/versions/node/v8.9.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:381:17)
    at Environment.run (/Users/me/.nvm/versions/node/v8.9.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:438:28)
    at env.lookup (/Users/me/.nvm/versions/node/v8.9.3/lib/node_modules/yo/lib/cli.js:156:11)

**Comment by kitzberger** [comment]
I'm using 2.0.5 and this is still an issue with my generator ;-/
